### ISSUE TITLE
Pager is not responsive and will overflow if table width is too small -- make pager maxSize customizable

### ISSUE THREAD

**Issue by YeomansIII** [swimlane/angular2-data-table#267]
```
[* ] feature request
```

**Current behavior**
If the table is too small (on mobile devices, this is the case) and five pages are listed in the pager, the pager will overflow to a new line.
![screenshot at 18-06-10](https://cloud.githubusercontent.com/assets/3809115/20121310/a55f40c6-a5de-11e6-8e80-70aaa03a7d3c.png)

**Expected behavior**
The pager should adjust the maxSize if there is not enough space.

**Reproduction of the problem**
Decrease your browser width or test on a mobile device.

**What is the motivation / use case for changing the behavior?**
Responsive design.

* **Table version:** ^1.3.1

* **Angular version:** ^2.1.2

* **Browser:** all

* **Language:** Typescript 2

Easiest solution I can think of is allowing the maxSize to be passed in as an input, I could implement this myself and make a pull request.  Have there been any other thoughts on adding responsive functionality?

**Comment by fenta23** [comment]
Have the same problem, i think you don't need the numbers in the pagination on mobil devices. I will hide them. What do you think? 
Did you see, i added the smooth scrolling on the table, so it feels more natural on iDevices...

Other question: do have the problem with the row width on mobil? i have 3 columns in flex mode and i get some space after the last column, and a scrollbar at the bottom:-(

**Comment by duard** [comment]
I have the same problem, how to fix it ?

**Comment by duard** [comment]
How can I fix this problem ?

![screenshot from 2017-07-16 09-29-09](https://user-images.githubusercontent.com/36894/28247564-46e8e138-6a09-11e7-9f4b-1c8455a2e8d9.png)

**Comment by arlowhite** [comment]
Here's the SCSS I have to override this:

```scss
// fix pager so that it doesn't wrap and uses available space
.ngx-datatable {
  .datatable-footer-inner {
    display: flex;
    flex-flow: row nowrap;  // can't wrap because footer height fixed
    justify-content: space-between;  // probably not needed because .page-count flex grows
    > .page-count {
      // remove padding so there's more room in-between
      padding-right: 0 !important;
    }
    > .datatable-pager {
      margin: 0 !important;
      // don't grow, otherwise pager won't be right-aligned
      flex: 0 0 auto !important;
      > .pager {
        // prevent numbers from wrapping
        display: flex !important;
        flex-flow: row nowrap;
      }
    }
  }
}
```

The other advantage of this is that the pager grows to the left instead of changing the width of the table. With this CSS, the left text will be covered by the pager when too narrow. Not sure what the best solution is. At the moment, wrapping the count and pager won't work.
